AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pediatric RCM Automation - Multi-Agent Billing Pipeline

Resources:
  PediatricRcmFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Root directory containing handler.py and requirements.txt
      CodeUri: ./
      Handler: handler.lambda_handler 
      Runtime: python3.13
      # Architectures: arm64 is cheaper and faster for Python 3.13
      Architectures:
        - arm64
      MemorySize: 512
      # Multi-agent loops can take time; 60s is safer than 30s
      Timeout: 60
      Environment:
        Variables:
          # Resolved from AWS Secrets Manager created earlier
          GOOGLE_API_KEY: '{{resolve:secretsmanager:PediatricRcmGeminiKey:SecretString:API_KEY}}'
      Policies:
        # Grants the Lambda permission to retrieve the API key at runtime
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:PediatricRcmGeminiKey-*'
      Events:
        BillingApi:
          Type: Api
          Properties:
            Path: /process-encounter
            Method: post

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/process-encounter/"
